#!/bin/bash

# GitHub repository setup script for CRM Database for Painting and Decorating Companies
# Generated by Prompt Maker

# Variables
REPO_NAME="crm_database_paint_decor"
DESCRIPTION="A comprehensive CRM database system for painting and decorating contractors"
WORKSPACE_DIR="/Users/tony/${REPO_NAME}"
GITHUB_USER="aigeezer"

# Create repository on GitHub
echo "Creating repository on GitHub..."
gh repo create $REPO_NAME --private --description "$DESCRIPTION"

# Initialize local repository
echo "Initializing local repository..."
cd "$WORKSPACE_DIR"
git init

# Add .gitignore file
cat > .gitignore << EOL
# IDE and editor files
.idea/
.vscode/
*.sublime-*
.DS_Store

# Environment files
.env
.env.*
!.env.example

# Logs
logs/
*.log

# Temporary files
tmp/
temp/
*.tmp

# Node modules (if developing frontend)
node_modules/

# Build outputs
dist/
build/
*.exe
*.dll
*.so
*.dylib

# Database files
*.db
*.sqlite
*.sqlite3

# Backup files
*.bak
*~
*.swp
EOL

# Add all files to git
git add .
git commit -m "Initial commit with database schema and documentation"

# Configure remote
echo "Configuring remote..."
git remote add origin https://github.com/$GITHUB_USER/$REPO_NAME.git

# Push to GitHub
echo "Pushing to GitHub..."
git push -u origin main

echo "Repository setup complete!"
echo "Your repository is available at: https://github.com/$GITHUB_USER/$REPO_NAME"
